exe{c-import}: {h c}{**} $lib

# As we only test the importation of the library
# and the compilation of its interface and implementation,
# all functions are purposely unused. With the following,
# we get rid of unused-function warnings.
#
switch $c.id
{
  case 'gcc' | 'clang' | 'clang-apple' | 'clang-emscripten'
    c.coptions += -Wno-unused-function
}
